authapp/urls.py
from django.urls import include, path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path(
        "profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from pathlib import Path
from time import time

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import gettext_lazy as _


def users_avatars_path(instance, filename):
    # file will be uploaded to
    #   MEDIA_ROOT / user_<username> / avatars / <filename>
    num = int(time() * 1000)
    suff = Path(filename).suffix
    return "user_{0}/avatars/{1}".format(instance.username, f"pic_{num}{suff}")


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username_validator = ASCIIUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    age = models.PositiveIntegerField(blank=True, null=True)
    avatar = models.ImageField(upload_to=users_avatars_path, blank=True, null=True)
    email = models.CharField(
        _("email address"),
        max_length=256,
        unique=True,
        error_messages={
            "unique": _("A user with that email address already exists."),
        },
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. \
            Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

authapp/forms.py
import os

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class CustomUserCreationForm(UserCreationForm):
    field_order = [
        "username",
        "password1",
        "password2",
        "email",
        "first_name",
        "last_name",
        "age",
        "avatar",
    ]

    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}

    def clean_avatar(self):
        arg_as_str = "avatar"
        if arg_as_str in self.changed_data and self.instance.avatar:
            if os.path.exists(self.instance.avatar.path):
                os.remove(self.instance.avatar.path)
        return self.cleaned_data.get(arg_as_str)

    def clean_age(self):
        data = self.cleaned_data.get("age")
        if data:
            if data < 10 or data > 100:
                raise ValidationError(_("Please, enter a valid age!"))
        return data

authapp/views.py
import os

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import get_user_model

from authapp import models

from authapp import forms


class CustomLoginView(LoginView):
    def form_valid(self, form):
        ret = super().form_valid(form)
        message = _("Яяяяяяяхаааааа бля!<br>Здаровки, %(username)s") % {
            "username": self.request.user.get_full_name()
            if self.request.user.get_full_name()
            else self.request.user.get_username()
        }
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        for _unused, msg in form.error_messages.items():
            messages.add_message(
                self.request,
                messages.WARNING,
                mark_safe(f"Чёт не то, братан, проверь данные:<br>{msg}"),
            )
        return self.render_to_response(self.get_context_data(form=form))


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.INFO, _("Пока, лодырь!"))
        return super().dispatch(request, *args, **kwargs)


class RegisterView(TemplateView):
    template_name = "registration/register.html"

    def post(self, request, *args, **kwargs):
        try:
            if all(
                (
                    request.POST.get("username"),
                    request.POST.get("email"),
                    request.POST.get("password1"),
                    request.POST.get("password1") == request.POST.get("password2"),
                )
            ):
                new_user = models.CustomUser.objects.create(
                    username=request.POST.get("username"),
                    first_name=request.POST.get("first_name"),
                    last_name=request.POST.get("last_name"),
                    age=request.POST.get("age") if request.POST.get("age") else 0,
                    avatar=request.FILES.get("avatar"),
                    email=request.POST.get("email"),
                )
                new_user.set_password(request.POST.get("password1"))
                new_user.save()
                messages.add_message(
                    request, messages.INFO, _("Регистрация успешна!!!!!")
                )
                return HttpResponseRedirect(reverse_lazy("authapp:login"))
        except Exception as exp:
            messages.add_message(
                request,
                messages.WARNING,
                mark_safe(f"Регистрация не удалась. Проверь поля:<br>{exp}"),
            )
            return HttpResponseRedirect(reverse_lazy("authapp:register"))


class ProfileEditView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = "edit_user.html"
    form_class = forms.CustomUserChangeForm

    def test_func(self):
        return True if self.request.user.pk == self.kwargs.get("pk") else False

    def get_success_url(self):
        return reverse_lazy("mainapp:main_page")

authapp/templates/edit_user.html
{% extends 'main.html' %}

{% block content %}
<div class="row justify-content-center my-2">
  <div class="col-lg-6">
    <h3>Редактирование профиля</h3>

    <div class="row justify-content-center">
      <div class="col-sm-7 col-md-5 col-lg-4">
        {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="" width="100%">
        {% else %}
        <img src="{{ MEDIA_URL }}avatar_default.svg" alt="" width="100%">
        {% endif %}
      </div>
    </div>

    <form method="post" class="mt-2" enctype="multipart/form-data">
      {% csrf_token %}
      <div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
          Username<span class="asteriskField">*</span> </label>
        <div class=""> <input type="text" name="username" maxlength="150" class="textinput textInput form-control"
            required id="id_username" value="{{ user.username }}"> <small id="hint_id_username"
            class="form-text text-muted">Required. 150 characters or fewer.
            Letters, digits and @/./+/-/_ only.</small> </div>
      </div>
      <div id="div_id_first_name" class="form-group"> <label for="id_first_name" class="">
          First name
        </label>
        <div class=""> <input type="text" name="first_name" maxlength="150" class="textinput textInput form-control"
            id="id_first_name" value="{{ user.first_name }}"> </div>
      </div>
      <div id="div_id_last_name" class="form-group"> <label for="id_last_name" class="">
          Last name
        </label>
        <div class=""> <input type="text" name="last_name" maxlength="150" class="textinput textInput form-control"
            id="id_last_name" value="{{ user.last_name }}"> </div>
      </div>
      <div id="div_id_age" class="form-group"> <label for="id_age" class="">
          Age
        </label>
        <div class=""> <input type="number" name="age" min="0" class="numberinput form-control" id="id_age"
            value="{{ user.age }}">
        </div>
      </div>
      <div id="div_id_avatar" class="form-group"> <label for="id_avatar" class="">
          Avatar
        </label>
        <div class=""> <input type="file" name="avatar" accept="image/*" class="clearablefileinput form-control-file"
            id="id_avatar"> </div>
      </div>
      <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
          Email address<span class="asteriskField">*</span> </label>
        <div class=""> <input type="text" name="email" maxlength="256" class="textinput textInput form-control"
            required="" id="id_email" value="{{ user.email }}">
        </div>
      </div>

      <button type=" submit" class="btn btn-primary btn-block">Сохранить</button>
    </form>
  </div>
</div>

{% endblock content %}