authapp/urls.py
from django.urls import include, path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path(
        "profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("addhouse/", views.AddHousePage.as_view(), name="add"),
    path("list_houses/", views.ListHousePage.as_view(), name="list_houses"),
    path("padiki/", views.PadikiPage.as_view(), name="padiki"),
    path("log_view/", views.LogView.as_view(), name="log"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
    path("support/", views.SupportView.as_view(), name="support"),
]

templates/includes/main_menu.html
{% load static %}
<nav class="menuu navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
      <img src="{% static 'img/logo.png' %}" alt="">
    </a>
    <button class="button-menu navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:main_page' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:main_page' %}"> <b> На главную </b> </a>
        </li>
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:padiki' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:padiki' %}"> Видео с полей </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:support' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:support' %}"> Техническая поддержка </a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:add' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:add' %}"> Добавить дом </a>
        </li>
        <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:list_houses' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:list_houses' %}"> Список домов </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Профиль
          </a>
          <div class="dropdown-menu" aria-labelledby="ddProfile">
            <a class="dropdown-item" href="{% url 'authapp:profile_edit' pk=request.user.pk %}">Редактировать
              профиль</a>
            <a class="dropdown-item" href="{% url 'mainapp:add' %}">Фотки листовок</a>
            <div class="dropdown-divider"></div>
            {% if user.is_superuser %}
            <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">Административный
              раздел</a>
            <a class="dropdown-item" href="{% url 'mainapp:log' %}" {% endif %}> Лог</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'authapp:logout' %}">Выход</a>
          </div>
        </li>


        {% else %}
        <li class="nav-item {% if request.resolver_match.view_name == 'authapp:login' %}active{% endif %}">
          <a class="nav-link" href="{% url 'authapp:login' %}">Войди чтоб видеть дома</a>
        </li>
        {% endif %}

      </ul>
      <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
    </div>
  </div>
</nav>

templates/includes/messages.html
<div class="position-absolute w-100" style="z-index: 1;">
    <div aria-live="polite" aria-atomic="true" class="m-2">
      <!-- Position it -->
      <div class="d-flex align-items-end flex-column">
  
        {% for message in messages %}
        <!-- Then put toasts within -->
        <div class="toast flex-fill w-100
      {% if message.level == 30 %}
      border-warning
      {% endif %}
        " role="alert" aria-live="assertive" aria-atomic="true"
          style="right: 0;">
          <div class="toast-header">
            <span class="mr-2"><i class="far fa-envelope"></i></span>
            <strong
              class="mr-auto {% if message.level == 30 %}text-warning{% endif %}">
              {{ message.tags|capfirst }} message</strong>
            <small class="text-muted">just now</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"
              aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="toast-body">
            {{ message }}
          </div>
        </div>
        {% if message.level > 20 %}
        <!-- If message will dissapere you will find message in console -->
        <script>
          console.log("{{ message }}");
        </script>
        {% endif %}
  
        {% endfor %}
  
      </div>
  
    </div>
  </div>