config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("addhouse/", views.AddHousePage.as_view(), name="add"),
    path("list_houses/", views.ListHousePage.as_view(), name="list_houses"),
    path("padiki/", views.PadikiPage.as_view(), name="padiki"),
    path("log_view/", views.LogView.as_view(), name="log"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
    path("support/", views.SupportView.as_view(), name="support"),
]

mainapp/models.py
# Create your models here.
from pathlib import Path
from time import time
from django.db import models
from authapp import models as modUs
from django.utils.translation import gettext_lazy as _


def photo_house(instance, filename):
    # file will be uploaded to
    #   MEDIA_ROOT / user_<username> / avatars / <filename>
    num = int(time() * 1000)
    suff = Path(filename).suffix
    return "user_{0}/photo_houses/{1}".format(
        instance.user.username, f"pic_{num}{suff}"
    )


class Street(models.Model):
    """
    Модель для создания улиц
    """
    name_street = models.CharField(
        unique=True, max_length=100, verbose_name="name_street"
    )

    def __str__(self):
        return f"{self.name_street}"


class Address(models.Model):
    """
    Модель для создания адресов. Адрес состоит из трех полей: id адреса,
    улица адреса и номер дома. Работаем по одному городу.
    """
    number_of_house = models.CharField(
        max_length=10, verbose_name="number_of_house")
    street = models.ForeignKey(Street, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Adress of work")
        verbose_name_plural = _("Adresses")

    def __str__(self):
        return f"{self.street.name_street}  {self.number_of_house}"


class Work(models.Model):
    """
    Модель для создания 1го рабочего прохода.
    """
    user = models.ForeignKey(modUs.CustomUser, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    photo = models.ImageField(
        upload_to=photo_house,
        blank=True,
        null=True,
        verbose_name="Photo of ad",
    )
    is_deleted = models.BooleanField(default=False)

mainapp/forms.py
import datetime
from django import forms
import requests

from mainapp import models as mainapp_models
from authapp import models as authapp_models


class CreateWorkForm(forms.ModelForm):
    class Meta:
        model = mainapp_models.Work
        exclude = ["user", "created_at", "is_deleted"]

    def clean_address(self):
        pk_entered_address = self.cleaned_data["address"]
        last_work_with_this_address = mainapp_models.Work.objects.filter(
            address=pk_entered_address
        )
        last_work = last_work_with_this_address.last()
        if last_work is not None:
            date_last_work = last_work.created_at.toordinal()
            now_date = datetime.datetime.now().toordinal()
            deltaTime = now_date - date_last_work
            if deltaTime < 14:
                raise forms.ValidationError("Эээээ.... 14 дней не прошло")
        return self.cleaned_data["address"]


class SupportForm(forms.Form):
    id_from = forms.IntegerField(widget=forms.HiddenInput)
    topic = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields["id_from"].initial = user.pk

    def send_message_to_mobile(self):
        """
        Функция для отправки сообщения на мобильный номер телефона.
        """
        msg = f'От кого: {self.cleaned_data["id_from"]}. Сообщение: {self.cleaned_data["message"]}'
        sms_api = f"https://sms.ru/sms/send?api_id=9501034C-74AE-EEFB-1C8B-E2998518C53E&to=79236508766,79132106042,79132408203,79132172595,79612404234&msg={msg}&json=1"
        res = requests.get(sms_api)

mainapp/views.py
from ast import Dict
import logging
from typing import Any
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.http import FileResponse, HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.generic import TemplateView
from mainapp import models as mainapp_models
from authapp import models as authapp_models
from django.views.generic import ListView, CreateView, View
from django.db.models import Q
from mainapp.forms import CreateWorkForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.conf import settings
from .forms import SupportForm
from django.views.generic.edit import FormView
from django.core.cache import cache
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.core.mail import EmailMessage

from mainapp import tasks as mainapp_tasks


logger = logging.getLogger(__name__)


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class ListHousePage(ListView):
    """
    Контроллер вывода списка пройденных домов.
    """

    model = mainapp_models.Work
    paginate_by = 20

    def get_queryset(self):
        """
        Измененный get_queryset для того чтобы отсеять удаленные рабочие листы,
        и также выводить рабочие листы, которые в названии улицы содержат 
        введенное значение.
        """
        query = self.request.GET.get("q")
        if query is not None:
            object_list = mainapp_models.Work.objects.filter(
                Q(address__street__name_street__icontains=query) & Q(
                    is_deleted=False)
            ).order_by("-created_at")
        else:
            object_list = mainapp_models.Work.objects.all().order_by("-created_at")
        return object_list


class AddHousePage(LoginRequiredMixin, CreateView):
    """
    Контролер добавления новых рабочих листов
    """
    model = mainapp_models.Work
    form_class = CreateWorkForm
    success_url = reverse_lazy("mainapp:add")

    def form_valid(self, form):
        """
        Кастомный метод для добавления в форму пользователя, который отправил
        запрос.       
        """
        new_house = form.save(commit=False)
        new_house.user = self.request.user
        new_house.save()
        return super().form_valid(form)


class PadikiPage(TemplateView):
    template_name = "mainapp/padiki.html"


class LogView(TemplateView):
    template_name = "mainapp/log_view.html"

    def get_context_data(self, **kwargs):
        context = super(LogView, self).get_context_data(**kwargs)
        log_slice = []
        with open(settings.LOG_FILE, "r") as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:  # first 1000 lines
                    break
                log_slice.insert(0, line)  # append at start
            context["log"] = "".join(log_slice)
        return context


class LogDownloadView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, "rb"))


class SupportView(TemplateView):
    """
    Контроллер для отправки сообщения в техническую поддержку.
    """
    template_name = "mainapp/support.html"

    def get_context_data(self, success=0, **kwargs: Any):
        context = super(SupportView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["form"] = SupportForm(user=self.request.user)
            context["success"] = success
        return context

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            cache_lock_flag = cache.get(
                f"mail_feedback_lock_{self.request.user.pk}")
            if not cache_lock_flag:
                cache.set(
                    f"mail_feedback_lock_{self.request.user.pk}",
                    "lock",
                    timeout=300,
                )
                messages.add_message(
                    self.request, messages.INFO, _("Message sended"))
                mainapp_tasks.send_feedback_mail.delay(
                    {
                        "id_from": self.request.POST.get("id_from"),
                        "topic": self.request.POST.get("topic"),
                        "message": self.request.POST.get("message"),
                    }
                )
            else:
                messages.add_message(
                    self.request,
                    messages.WARNING,
                    _("You can send only one message per 5 minutes"),
                )
        return HttpResponseRedirect(reverse_lazy("mainapp:support"))

mainapp/templates/mainapp/index.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<div class="main_page">
    <img class="photoAgent" src="{% static 'img/agent07.jpeg' %}">
</div>



{% endblock content %}

mainapp/templates/mainapp/log_view.html
{% extends 'main.html' %}

{% block content %}
<div class="row justify-content-end my-2">
  <div class="col-sm-4 col-lg-2">
    <a href="{% url 'mainapp:log_download' %}" class="btn btn-primary btn-block"
      role="button">Скачать</a>
  </div>
</div>
<p>
<div class="text-center text-muted"><small>First 1000 lines of log file</small></div>
<pre>{{ log }}</pre>
</p>
{% endblock content %}

mainapp/templates/mainapp/padiki.html
{% extends 'main.html' %}

{% load static %}

{% block content %}


<div class = "vidos" data-player-id="7a83aeb0-04e1-4ee7-9164-90ee5e4fa94f"><script src="//cdn.flowplayer.com/players/5b8a3d51-2a99-4d09-9c6e-d35c70f72f32/native/flowplayer.async.js">{"src": "8cbf6eb1-c33d-4e32-83d0-88ec5fdb8053"}</script></div>

{% endblock content %}

mainapp/templates/mainapp/support.html
{% extends 'main.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row justify-content-center pt-3">
    <div class="col-md-12 col-lg-8">
        <form method="post" enctype="multipart/form-data">
            {% if form.message.errors %} <div>
                <h2> <strong> {{form.message.errors}} </strong> </h2>
            </div>
            {% endif %}
            {% if success %} <div>
                <h2> Сообщение отправлено!!! </h2>
            </div>
            {% endif %}
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-block"> Отправить сообщение </button>
        </form>
    </div>
</div>


{% endblock content %}

mainapp/templates/mainapp/work_form.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block content %}
<div class="row justify-content-center pt-3">
    <div class="col-md-12 col-lg-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit"
          class="btn btn-primary btn-block">Опубликовать</button>
      </form>
    </div>
  </div>
{% endblock content %}

mainapp/templates/mainapp/work_list.html
{% extends 'main.html' %}

{% load static %}

{% block content %}
<div class="houses">

    <form action="{% url 'mainapp:list_houses' %}" method="get">
        <input class="findHouse" name="q" type="text" placeholder="Найди дом...">
    </form>
    {% for item in object_list %}
    <div class="address_work">
        <br>
        <div> Что ходил: <b>{{item.address.street.name_street}} {{item.address.number_of_house}} </b>
            <div> Кто ходил: {{item.user.username}} </div>
            <div> Когда ходил: <b> {{item.created_at|date}} </b>
                {% if item.photo %}
                <a href="{{ item.photo.url }}" class="lightzoom "><img class="photo col-3 text-right"
                        src="{{ item.photo.url }}"> </a>

                {% endif %}
            </div>
            {% endfor %}

        </div>


        <div class="kambala"> <img src="{% static 'img/kambala.jpeg' %}"></div>

        {% endblock content %}