authapp/urls.py
from django.urls import include, path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path(
        "profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("addhouse/", views.AddHousePage.as_view(), name="add"),
    path("list_houses/", views.ListHousePage.as_view(), name="list_houses"),
    path("padiki/", views.PadikiPage.as_view(), name="padiki"),
    path("log_view/", views.LogView.as_view(), name="log"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
    path("support/", views.SupportView.as_view(), name="support"),
]

mainapp/models.py
# Create your models here.
from pathlib import Path
from time import time
from django.db import models
from authapp import models as modUs
from django.utils.translation import gettext_lazy as _


def photo_house(instance, filename):
    # file will be uploaded to
    #   MEDIA_ROOT / user_<username> / avatars / <filename>
    num = int(time() * 1000)
    suff = Path(filename).suffix
    return "user_{0}/photo_houses/{1}".format(
        instance.user.username, f"pic_{num}{suff}"
    )


class Street(models.Model):
    """
    Модель для создания улиц
    """
    name_street = models.CharField(
        unique=True, max_length=100, verbose_name="name_street"
    )

    def __str__(self):
        return f"{self.name_street}"


class Address(models.Model):
    """
    Модель для создания адресов. Адрес состоит из трех полей: id адреса,
    улица адреса и номер дома. Работаем по одному городу.
    """
    number_of_house = models.CharField(
        max_length=10, verbose_name="number_of_house")
    street = models.ForeignKey(Street, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Adress of work")
        verbose_name_plural = _("Adresses")

    def __str__(self):
        return f"{self.street.name_street}  {self.number_of_house}"


class Work(models.Model):
    """
    Модель для создания 1го рабочего прохода.
    """
    user = models.ForeignKey(modUs.CustomUser, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    photo = models.ImageField(
        upload_to=photo_house,
        blank=True,
        null=True,
        verbose_name="Photo of ad",
    )
    is_deleted = models.BooleanField(default=False)

templates/main.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- ChartJS -->
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

  <!-- FontAwesome -->
  <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/my.css' %}">

  <title>
    {% block title %}
    Смотри на жизни проще!
    {% endblock title %}
  </title>
</head>

<body>

  {% include 'includes/main_menu.html' %}

  {% block messages %}
  {% include 'includes/messages.html' %}
  {% endblock messages %}

  <div class="content container-md">

    {% block content %}

    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur
    optio est esse? Veritatis laborum expedita
    quibusdam numquam! Expedita amet nisi dolor similique autem, mollitia
    ipsa et, natus vel explicabo
    reprehenderit?

    {% endblock content %}

  </div>

  <!-- Footer -->

  <div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong class="soul">Вкус агента </strong> <br>
          <small> © Создатель: Данил Гущин </small>
        </p>
        <p>
        <ul class="list-unstyled">
          <li><a href="{% url 'mainapp:main_page' %}">Домашняя</a></li>

          {% if user.is_authenticated %}
          <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
          {% else %}
          <li><a href="{% url 'authapp:login' %}">Войти</a></li>
          {% endif %}





          <!-- JavaScript section -->
          <!-- Bootstrap -->
          <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap.min.js' %}"></script>

          <!-- ChartJs -->
          <script src="{% static 'js/Chart.min.js' %}"></script>

          <!-- FontAwesome -->
          <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

          {% block js %}
          <script>
            $(document).ready(function () {

              {% if messages %}
              // Toasts
              $(".toast").toast({ delay: 5000 });
              $(".toast").toast("show");
              {% endif %}

            });
          </script>
          {% endblock js %}

          <!-- JQuery-->

          <script src="https://code.jquery.com/jquery-3.6.3.min.js"
            integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

          <!-- Select2 -->
          <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
          <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

          <script>
            $(document).ready(function () {
              $('#id_address').select2();
            });
          </script>

          <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
          <script type="text/javascript" src="{% static 'js/lightzoom.js' %}"></script>
          <script type="text/javascript">jQuery('.lightzoom').lightzoom({ speed: 400, viewTitle: true });</script>
</body>

</html>